services:
  visits-service:
    build: .
    container_name: visits-service
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: visits-postgres
    environment:
      POSTGRES_USER: visits
      POSTGRES_PASSWORD: visits
      POSTGRES_DB: visits
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
