services:
  api-service:
    build: .
    container_name: api-service
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:16-alpine
    container_name: api-postgres
    environment:
      POSTGRES_USER: visits
      POSTGRES_PASSWORD: visits
      POSTGRES_DB: visits
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
